"""empty message

Revision ID: b8f6e85fa7be
Revises: d6110c5c3f4c
Create Date: 2025-09-05 13:32:36.100514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b8f6e85fa7be"
down_revision: Union[str, Sequence[str], None] = "d6110c5c3f4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pokemon",
        sa.Column("image_directory", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "image_directory")
    # ### end Alembic commands ###
