name: Release

on:
  push: 
    branches: 
      - master

jobs: 
  release:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
    uses: actions/checkout@v4
    - name: Setup Node.
    uses: actions/setup-node@v4
    with: 
      node-version: 20
    - name: Install frontend deps
    working-directory: frontend
    run: npm ci
    - name: Build frontend 
    working-directory: frontend
    run: npm run build
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: frontend
    - name: Release to GitHub
      working-directory: frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: enter author name
        GIT_AUTHOR_EMAIL: person@example.com
        GIT_COMMITTER_NAME: enter name
        GIT_COMMITTER_EMAIL: committer@example.com
      run: npx semantic-release